apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    # Especifica que solo puede ser usado por un pod a la vez
    - ReadWriteOnce
  hostPath:
    path: "/test"
